{
 "title": "Kubernetes - ft_services dashboard by julnolle",
 "description": "Kubernetes Aggregated Container Stats by Namespace and Container",
 "tags": [
  "kubernetes",
  "influxdb",
  "Container",
  "Telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": "SHOW TAG VALUES FROM \"kubernetes_pod_container\" WITH KEY=namespace"
   },
   {
    "name": "name",
    "label": "Container Name",
    "query": "SHOW TAG VALUES FROM \"kubernetes_pod_container\" WITH KEY=container_name WHERE \"namespace\" =~ /^$ns$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT count(distinct(node_name)) FROM (SELECT mean(\"cpu_usage_core_nanoseconds\") AS \"mean_cpu_usage_core_nanoseconds\" FROM \"kubernetes_pod_container\" WHERE time > now() - 1m GROUP BY time(1h), \"node_name\" LIMIT 1) FILL(previous)",
     "select": [
      [
       { "params": [ "cpu_usage_core_nanoseconds" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT count(pod_name) FROM (SELECT mean(\"cpu_usage_core_nanoseconds\") AS \"mean_cpu_usage_core_nanoseconds\" FROM \"kubernetes_pod_container\" WHERE time > now() - 1m AND namespace =~ /^$ns$/ AND container_name =~ /^$name$/ GROUP BY time(1h), \"pod_name\" LIMIT 1) FILL(previous)",
     "select": [
      [
       { "params": [ "cpu_usage_core_nanoseconds" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT count(container_name) FROM (SELECT mean(\"cpu_usage_core_nanoseconds\") AS \"mean_cpu_usage_core_nanoseconds\" FROM \"kubernetes_pod_container\" WHERE time > now() - 1m AND namespace =~ /^$ns$/ AND container_name =~ /^$name$/ GROUP BY time(1h), \"container_name\",\"pod_name\" LIMIT 1) FILL(previous)\n",
     "select": [
      [
       { "params": [ "cpu_usage_core_nanoseconds" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU - Milicores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Millicores - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$ns$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Usage - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    },
    {
     "alias": "RSS - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_rss_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    },
    {
     "alias": "Page Faults - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_page_faults" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    },
    {
     "alias": "Major Page Faults - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_major_page_faults" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "RX - $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_network",
     "query": "SELECT mean(\"value\") FROM \"network/rx_rate\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$ns$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^$name.*/" }
     ]
    },
    {
     "alias": "TX - $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_network",
     "query": "SELECT mean(\"value\") FROM \"network/tx_rate\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Used - $tag_volume_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "volume_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kubernetes_pod_volume",
       "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
        { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
       ]
      },
      {
       "alias": "Available - $tag_volume_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "volume_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kubernetes_pod_volume",
       "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "available_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
        { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}